services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=rsshub
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD", 'pg_isready -U user -d rsshub']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
